# Generated by Django 3.1.4 on 2020-12-26 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_type', models.CharField(choices=[('P', 'Problems'), ('C', 'Consequences'), ('O', 'Opportunities'), ('CG', 'Career Goals')], max_length=2)),
                ('title', models.CharField(max_length=150)),
                ('subtitle', models.CharField(max_length=500)),
                ('content', models.TextField()),
                ('date_added', models.DateTimeField()),
            ],
        ),
    ]
