# Generated by Django 3.1.4 on 2020-12-26 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Story',
        ),
    ]
