# Generated by Django 3.1.4 on 2020-12-26 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_story'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Story',
        ),
    ]
